'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

    '''<summary>
    '''lblHelperType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHelperType As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlHelperType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHelperType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTabs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTabType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTabType As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''rdoTabType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoTabType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblTabFade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTabFade As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkUseTabFade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseTabFade As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlAccordion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccordion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlCarousel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCarousel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblShowCarCaptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowCarCaptions As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkShowCarCaptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCarCaptions As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblShowCarNavs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowCarNavs As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkCarShowCarNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCarShowCarNav As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCarStretch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarStretch As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkCarStretch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCarStretch As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCarInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarInterval As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtCarInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarInterval As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlButtonGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButtonGroup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblbtnJustify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbtnJustify As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkJustify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkJustify As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBtnVerticle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBtnVerticle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkVert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVert As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblBtnSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBtnSize As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlBtnSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBtnSize As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblBtnStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBtnStyle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlBtnStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBtnStyle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlFlipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFlipper As Global.System.Web.UI.WebControls.Panel
End Class
